[package]
name = "tunnel2tunnel-core"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx      = { workspace = true }
uuid      = { workspace = true }
time      = { workspace = true }
serde     = { workspace = true }
thiserror = { workspace = true }
tracing   = { workspace = true }
argon2    = { workspace = true }
sha2      = { workspace = true }
base64    = { workspace = true }
ipnetwork = { workspace = true }
glob      = { workspace = true }
regex     = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
