from __future__ import annotations

import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
HOOK = ROOT / "scripts" / "°base" / "git" / "hooks" / "commit" / "require_yarn_4.py"


def run_git(repo: Path, *args: str, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", *args],
        cwd=repo,
        capture_output=True,
        text=True,
        check=check,
    )
# end def


def init_repo(repo: Path, enabled: bool | None = True) -> None:
    repo.mkdir(parents=True)
    run_git(repo, "init")
    settings: dict[str, object] = {}
    if enabled is not None:
        settings["pre_commit"] = {"yarn@4": {"enabled": enabled}}
    # end if
    write_and_stage(repo, "ai/tool-settings/settings.json", json.dumps(settings))
# end def


def write_and_stage(repo: Path, relative: str, text: str, force: bool = False) -> None:
    path = repo / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    args = ["add"]
    if force:
        args.append("--force")
    # end if
    args.extend(["--", relative])
    run_git(repo, *args)
# end def


def add_valid_project(repo: Path, root: str = "") -> None:
    prefix = f"{root.rstrip('/')}/" if root else ""
    write_and_stage(
        repo,
        f"{prefix}package.json",
        json.dumps({"name": "demo", "packageManager": "yarn@4.13.0"}),
    )
    write_and_stage(
        repo,
        f"{prefix}yarn.lock",
        '# Generated by Yarn\n\n__metadata:\n  version: 8\n  cacheKey: "10c0"\n',
    )
# end def


def run_hook(repo: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(HOOK)],
        cwd=repo,
        capture_output=True,
        text=True,
    )
# end def


class Yarn4HookTests(unittest.TestCase):
    def test_no_node_files_is_silent(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp) / "repo"
            init_repo(repo)

            result = run_hook(repo)

            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertEqual(result.stderr, "")
        # end with
    # end def

    def test_missing_setting_defaults_to_enabled(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp) / "repo"
            init_repo(repo, enabled=None)
            write_and_stage(repo, "package.json", json.dumps({"name": "demo"}))

            result = run_hook(repo)

            self.assertEqual(result.returncode, 1)
            self.assertIn("not covered by a Yarn 4 project root", result.stderr)
        # end with
    # end def

    def test_tracked_disable_allows_legacy_project(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp) / "repo"
            init_repo(repo, enabled=False)
            write_and_stage(repo, "package.json", json.dumps({"packageManager": "yarn@2.4.3"}))
            write_and_stage(repo, "yarn.lock", "__metadata:\n  version: 4\n")

            result = run_hook(repo)

            self.assertEqual(result.returncode, 0, result.stderr)
        # end with
    # end def

    def test_valid_yarn_4_project_and_workspace_pass(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp) / "repo"
            init_repo(repo)
            add_valid_project(repo)
            write_and_stage(repo, "packages/app/package.json", json.dumps({"name": "app"}))
            write_and_stage(repo, ".yarnrc.yml", "nodeLinker: pnp\n")

            result = run_hook(repo)

            self.assertEqual(result.returncode, 0, result.stderr)
        # end with
    # end def

    def test_valid_local_release_and_zero_install_files_pass(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp) / "repo"
            init_repo(repo)
            add_valid_project(repo)
            write_and_stage(
                repo,
                ".yarnrc.yml",
                "enableGlobalCache: false\nyarnPath: .yarn/releases/yarn-4.13.0.cjs\n",
            )
            write_and_stage(repo, ".yarn/releases/yarn-4.13.0.cjs", "Yarn 4 bundle\n")
            write_and_stage(repo, ".yarn/cache/demo-npm-1.0.0.zip", "archive\n")
            write_and_stage(repo, ".pnp.cjs", "PnP loader\n")

            result = run_hook(repo)

            self.assertEqual(result.returncode, 0, result.stderr)
        # end with
    # end def

    def test_nested_independent_yarn_projects_pass(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp) / "repo"
            init_repo(repo)
            add_valid_project(repo, "frontend")
            add_valid_project(repo, "tools/editor")

            result = run_hook(repo)

            self.assertEqual(result.returncode, 0, result.stderr)
        # end with
    # end def

    def test_old_lock_versions_are_rejected(self) -> None:
        locks = {
            "classic": "# yarn lockfile v1\n",
            "yarn_2": "__metadata:\n  version: 4\n",
            "yarn_3": "__metadata:\n  version: 6\n",
        }
        for name, lock in locks.items():
            with self.subTest(name=name), tempfile.TemporaryDirectory() as tmp:
                repo = Path(tmp) / "repo"
                init_repo(repo)
                add_valid_project(repo)
                write_and_stage(repo, "yarn.lock", lock)

                result = run_hook(repo)

                self.assertEqual(result.returncode, 1)
                self.assertIn("__metadata.version 8", result.stderr)
            # end with
        # end for
    # end def

    def test_invalid_package_manager_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp) / "repo"
            init_repo(repo)
            add_valid_project(repo)
            write_and_stage(repo, "package.json", json.dumps({"packageManager": "yarn@4"}))

            result = run_hook(repo)

            self.assertEqual(result.returncode, 1)
            self.assertIn("exact Yarn 4 version", result.stderr)
        # end with
    # end def

    def test_legacy_and_competing_files_are_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp) / "repo"
            init_repo(repo)
            add_valid_project(repo)
            write_and_stage(repo, ".yarnrc", "--install.ignore-engines true\n")
            write_and_stage(repo, "package-lock.json", "{}\n")
            write_and_stage(repo, ".yarn/releases/yarn-2.4.3.cjs", "old yarn\n")

            result = run_hook(repo)

            self.assertEqual(result.returncode, 1)
            self.assertIn("legacy .yarnrc", result.stderr)
            self.assertIn("competing package-manager lockfile", result.stderr)
            self.assertIn("exact Yarn 4 .cjs", result.stderr)
        # end with
    # end def

    def test_tracked_node_modules_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp) / "repo"
            init_repo(repo)
            add_valid_project(repo)
            write_and_stage(repo, "node_modules/demo/index.js", "module.exports = 1;\n", force=True)

            result = run_hook(repo)

            self.assertEqual(result.returncode, 1)
            self.assertIn("node_modules must never be tracked", result.stderr)
        # end with
    # end def

    def test_ignored_node_modules_warns_without_failing(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp) / "repo"
            init_repo(repo)
            write_and_stage(repo, ".gitignore", "node_modules/\n")
            ignored = repo / "node_modules" / "demo" / "index.js"
            ignored.parent.mkdir(parents=True)
            ignored.write_text("module.exports = 1;\n", encoding="utf-8")

            result = run_hook(repo)

            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertIn("warning: ignored local node_modules", result.stderr)
        # end with
    # end def

    def test_local_other_pre_commit_setting_is_allowed(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp) / "repo"
            init_repo(repo)
            local = repo / "ai" / "tool-settings" / "settings.local.json"
            local.write_text(json.dumps({"pre_commit": {"other": {"enabled": False}}}), encoding="utf-8")

            result = run_hook(repo)

            self.assertEqual(result.returncode, 0, result.stderr)
        # end with
    # end def

    def test_local_yarn_setting_is_configuration_error(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp) / "repo"
            init_repo(repo)
            local = repo / "ai" / "tool-settings" / "settings.local.json"
            local.write_text(json.dumps({"pre_commit": {"yarn@4": {"enabled": False}}}), encoding="utf-8")

            result = run_hook(repo)

            self.assertEqual(result.returncode, 2)
            self.assertIn("shared repository policy", result.stderr)
        # end with
    # end def

    def test_yarn_path_must_reference_yarn_4(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp) / "repo"
            init_repo(repo)
            add_valid_project(repo)
            write_and_stage(repo, ".yarnrc.yml", "yarnPath: .yarn/releases/yarn-2.4.3.cjs\n")

            result = run_hook(repo)

            self.assertEqual(result.returncode, 1)
            self.assertIn("yarnPath must reference an exact Yarn 4 release", result.stderr)
        # end with
    # end def

    def test_yarn_artifact_without_manifest_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp) / "repo"
            init_repo(repo)
            write_and_stage(repo, ".yarnrc.yml", "nodeLinker: pnp\n")

            result = run_hook(repo)

            self.assertEqual(result.returncode, 1)
            self.assertIn("no package.json is tracked", result.stderr)
        # end with
    # end def

    def test_hook_is_registered_in_both_manifests(self) -> None:
        for relative in (".pre-commit-config.yaml", ".pre-commit-hooks.yaml"):
            with self.subTest(relative=relative):
                text = (ROOT / relative).read_text(encoding="utf-8")
                self.assertIn("id: require-yarn-4", text)
                self.assertIn("require_yarn_4.py", text)
                self.assertIn("pass_filenames: false", text)
            # end with
        # end for
    # end def
# end class


if __name__ == "__main__":
    unittest.main()
