"""
Auto-installs pre-commit hooks when this package is imported.
Runs automatically if you do `python -m hooks` or `python -c 'import hooks'`
"""

from __future__ import annotations

import stat
import subprocess
import sys
from pathlib import Path

PRE_PUSH_MARKER = "Auto-generated by scripts/°base/git/hooks/install — do not edit by hand."


def _git_toplevel(cwd: Path) -> Path | None:
    result = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        cwd=cwd,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        return None
    return Path(result.stdout.strip())


def _install_pre_push_hook(cwd: Path) -> None:
    """Write a small trampoline at .git/hooks/pre-push that execs our tracked
    push hook script, which itself preserves git-lfs's pre-push behavior.
    """
    toplevel = _git_toplevel(cwd)
    if toplevel is None:
        print("Warning: could not resolve git toplevel for pre-push hook install.", file=sys.stderr)
        return

    hooks_dir = toplevel / ".git" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    target = hooks_dir / "pre-push"

    if target.exists() and PRE_PUSH_MARKER not in target.read_text(encoding="utf-8", errors="ignore"):
        backup = hooks_dir / "pre-push.pre-base-backup"
        if not backup.exists():
            backup.write_bytes(target.read_bytes())
            print(f"Backed up existing pre-push hook to {backup}", file=sys.stderr)

    target.write_text(
        "#!/usr/bin/env sh\n"
        f"# {PRE_PUSH_MARKER}\n"
        "set -eu\n"
        'repo_root="$(git rev-parse --show-toplevel)"\n'
        'exec "$repo_root/scripts/°base/git/hooks/push/pre_push.sh" "$@"\n',
        encoding="utf-8",
    )
    target.chmod(target.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print("✓ pre-push hook installed", file=sys.stderr)


def _list_hooks():
    try:
        repo_root = Path(__file__).parent.parent
        hooks = repo_root / '.git' / 'hooks'
        installed = []
        for hook in hooks.iterdir():
            if not hook.is_file():
                continue
            # end if
            if hook.name.endswith(".sample"):
                continue
            # end if
            installed.append(hook)
        # end for

        print(f"Installed git        hooks: {[h.name for h in installed]}", file=sys.stderr)

        installed_precommit = []
        for file in installed:
            with open(file, "r") as f:
                txt = f.read()
                if not 'pre-commit' in txt:
                    continue
                # end if
            # end with
            installed_precommit.append(file)
        # end for

        print(f"Installed pre-commit hooks: {[h.name for h in installed_precommit]}", file=sys.stderr)
    except Exception as e:
        print(f"Warning: could not read installed hooks: {e}", file=sys.stderr)
    # end try
# end def


def _install_hooks():
    """Install pre-commit hooks during package import/installation."""
    _list_hooks()
    try:
        repo_root = Path(__file__).parent.parent

        # Clear any explicit core.hooksPath config that might interfere
        subprocess.run(
            ["git", "config", "--unset-all", "core.hooksPath"],
            cwd=repo_root,
            capture_output=True,
        )

        # Install pre-commit hooks
        result = subprocess.run(
            [sys.executable, "-m", "pre_commit", "install", "--hooks-type", "commit-msg"],
            cwd=repo_root,
            capture_output=True,
        )

        if result.returncode == 0:
            print("✓ Pre-commit hooks installed", file=sys.stderr)
        else:
            print(
                f"Warning: pre-commit hooks installation had issues: {result.stderr.decode()}",
                file=sys.stderr,
            )

        _install_pre_push_hook(repo_root)
    except Exception as e:
        print(f"Warning: could not install pre-commit hooks: {e}", file=sys.stderr)
    # end try
    _list_hooks()
# end def

_install_hooks()
