#!/usr/bin/env python3
"""
Setup.py that installs pre-commit hooks during package setup.
"""

from __future__ import annotations

import stat
import subprocess
import sys
from pathlib import Path

from setuptools import find_packages, setup

PRE_PUSH_MARKER = "Auto-generated by scripts/°base/git/hooks/install — do not edit by hand."


def _git_toplevel(cwd: Path) -> Path | None:
    result = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        cwd=cwd,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        return None
    return Path(result.stdout.strip())


def _install_pre_push_hook(cwd: Path) -> None:
    """Write a small trampoline at .git/hooks/pre-push that execs our tracked
    push hook script, which itself preserves git-lfs's pre-push behavior.
    """
    toplevel = _git_toplevel(cwd)
    if toplevel is None:
        print("Warning: could not resolve git toplevel for pre-push hook install.", file=sys.stderr)
        return

    hooks_dir = toplevel / ".git" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    target = hooks_dir / "pre-push"

    if target.exists() and PRE_PUSH_MARKER not in target.read_text(encoding="utf-8", errors="ignore"):
        backup = hooks_dir / "pre-push.pre-base-backup"
        if not backup.exists():
            backup.write_bytes(target.read_bytes())
            print(f"Backed up existing pre-push hook to {backup}", file=sys.stderr)

    target.write_text(
        "#!/usr/bin/env sh\n"
        f"# {PRE_PUSH_MARKER}\n"
        "set -eu\n"
        'repo_root="$(git rev-parse --show-toplevel)"\n'
        'exec "$repo_root/scripts/°base/git/hooks/push/pre_push.sh" "$@"\n',
        encoding="utf-8",
    )
    target.chmod(target.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print("✓ pre-push hook installed", file=sys.stderr)


def _install_hooks():
    """Install pre-commit hooks during setup."""
    try:
        repo_root = Path(__file__).parent.parent

        # Clear any explicit core.hooksPath config that might interfere
        subprocess.run(
            ["git", "config", "--unset-all", "core.hooksPath"],
            cwd=repo_root,
            capture_output=True,
        )

        # Install pre-commit hooks
        result = subprocess.run(
            [sys.executable, "-m", "pre_commit", "install", "--hooks-type", "commit-msg"],
            cwd=repo_root,
            capture_output=True,
        )

        if result.returncode == 0:
            print("✓ Pre-commit hooks installed", file=sys.stderr)

        _install_pre_push_hook(repo_root)
    except Exception as e:
        print(f"Warning: could not install pre-commit hooks: {e}", file=sys.stderr)


# Install hooks during setup
_install_hooks()

setup(
    packages=find_packages(),
)
