[Definition]
# Matches lines written by tunnel2tunnel to FAIL2BAN_LOG_PATH
# Format mirrors sshd: "... Failed publickey for invalid user <fp> from <IP> port <p> ssh2"
failregex = ^.+ t2t sshd\[\d+\]: Failed publickey for invalid user .+ from <HOST> port \d+ ssh2$
ignoreregex =
