[package]
name = "tunnel2tunnel-web"
version = "0.1.0"
edition = "2021"

[dependencies]
tunnel2tunnel-core          = { path = "../tunnel2tunnel-core" }
axum                        = { workspace = true }
tower-sessions              = { workspace = true }
tower-sessions-sqlx-store   = { workspace = true }
tower-http                  = { workspace = true }
serde                       = { workspace = true }
serde_json                  = { workspace = true }
tokio                       = { workspace = true }
tracing                     = { workspace = true }
thiserror                   = { workspace = true }
time                        = { workspace = true }
uuid                        = { workspace = true }
anyhow                      = { workspace = true }
sqlx                        = { workspace = true }
sentry                      = { workspace = true, features = ["tower-axum-matched-path"] }
tower                       = { workspace = true }
