from __future__ import annotations

import ast
import json
from typing import Any

from .commands import _bash_pattern_to_prefix

RULES_GENERATED_MARKER = "# Generated by scripts/°base/ai/settings/sync.py; do not edit directly."


def render_codex_rules(shared: dict[str, Any]) -> str:
    """Render `permissions.allow`/`permissions.deny` bash entries into a Codex
    `.rules` file (see https://developers.openai.com/codex/rules). Only
    `type == "bash"` entries translate; everything else governs filesystem
    reads or skill invocation, which Codex rules don't cover."""
    permissions = shared.get("permissions") or {}
    lines = [RULES_GENERATED_MARKER, ""]
    skipped: list[dict[str, Any]] = []
    for bucket, decision in (("allow", "allow"), ("deny", "forbidden")):
        for entry in permissions.get(bucket) or []:
            if not isinstance(entry, dict) or entry.get("type") != "bash":
                continue
            command = entry.get("command", "")
            prefix = _bash_pattern_to_prefix(command)
            if prefix is None:
                skipped.append(entry)
                continue
            pattern_literal = "[" + ", ".join(json.dumps(tok, ensure_ascii=False) for tok in prefix) + "]"
            lines.append(f'prefix_rule(pattern = {pattern_literal}, decision = "{decision}")')

    if skipped:
        lines.append("")
        lines.append(
            f"# {len(skipped)} command permission(s) could not be translated to a Codex "
            "prefix rule and were skipped (compound/redirected/substituted commands)."
        )
        for entry in skipped:
            lines.append(f"# {json.dumps(entry, ensure_ascii=False)}")
    return "\n".join(lines) + "\n"


def parse_codex_rules(text: str) -> dict[str, list[dict[str, Any]]]:
    """Parse `prefix_rule(...)` calls back out of a `.rules` file. Starlark's
    subset of syntax used here (literals, lists, kwargs, comments) is valid
    Python syntax, so the stdlib `ast` module is a safe, dependency-free
    reader. `prompt`-decision rules and rules with non-flat patterns have no
    Claude equivalent and are skipped rather than merged back."""
    result: dict[str, list[dict[str, Any]]] = {"allow": [], "deny": []}
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return result

    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        if getattr(node.func, "id", None) != "prefix_rule":
            continue

        kwargs: dict[str, Any] = {}
        for kw in node.keywords:
            if kw.arg is None:
                continue
            try:
                kwargs[kw.arg] = ast.literal_eval(kw.value)
            except (ValueError, SyntaxError):
                kwargs[kw.arg] = None

        pattern = kwargs.get("pattern")
        if not isinstance(pattern, list) or not pattern or not all(isinstance(tok, str) for tok in pattern):
            continue

        decision = kwargs.get("decision", "allow")
        if decision == "allow":
            bucket = "allow"
        elif decision == "forbidden":
            bucket = "deny"
        else:
            continue

        command = " ".join(pattern) + ":*"
        result[bucket].append({"type": "bash", "command": command})

    return result
