from __future__ import annotations

import subprocess
from pathlib import Path


def _git_root() -> Path:
    result = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        capture_output=True,
        text=True,
    )
    if result.returncode == 0 and result.stdout.strip():
        return Path(result.stdout.strip())
    return Path.cwd()


TRACKED_SHARED = Path("ai/tool-settings/settings.json")
LOCAL_SHARED = Path("ai/tool-settings/settings.local.json")
CLAUDE_SETTINGS = Path(".claude/settings.json")
CLAUDE_LOCAL = Path(".claude/settings.local.json")
CODEX_HOOKS = Path(".codex/hooks.json")
CODEX_LOCAL_HOOKS = Path(".codex/hooks.local.json")
CODEX_CONFIG = Path.home() / ".codex" / "config.toml"
CODEX_RULES = Path(".codex/rules/generated.rules")
CODEX_RULES_LOCAL = Path(".codex/rules/generated.local.rules")
CODEX_PROJECT_CONFIG = Path(".codex/config.toml")
CLAUDE_MCP = Path(".mcp.json")
SHARED_SKILLS = Path("ai/skills")
AGENTS_SKILLS = Path(".agents/skills")
CLAUDE_SKILLS = Path(".claude/skills")
CLAUDE_COMMANDS = Path(".claude/commands")
CODEX_COMMANDS = Path(".codex/commands")
GENERATED_MARKER = "<!-- Generated by scripts/°base/ai/settings/sync.py; do not edit directly. -->"
