#!/usr/bin/env bash
# scripts/°base/init/checkout.sh
#
# One-shot repo setup: installs git hooks (pre-commit framework + git-lfs)
# and cleans up stale yorkie hooks left behind by the old Vue CLI tooling.
#
# Intended to be run:
#   - By the Claude SessionStart hooks (automatic)
#   - After `git clone` / `git checkout` (manual or via post-checkout)
#   - Idempotent: safe to run multiple times.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOKS_DIR="$REPO_ROOT/.git/hooks"
TOOL_PATH_PREFIX="$HOME/.local/bin:$HOME/.cargo/bin:$HOME/.pyenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/local/sbin"
export PATH="$TOOL_PATH_PREFIX:$PATH"

# ─── 0. Ensure required git origins are configured ──────────────────────────
REQUIRED_ORIGINS=(
  "base https://github.com/luckydonald/base.git"
  "empty https://github.com/EmptyAAS/empty.git"
)

ensure_required_origins() {
  local name url origin_url remote
  origin_url="$(git remote get-url origin 2>/dev/null || true)"
  for remote in "${REQUIRED_ORIGINS[@]}"; do
    name="${remote%% *}"
    url="${remote#* }"
    # Skip if origin already covers this URL (e.g. in the base repo itself)
    [ "$origin_url" = "$url" ] && continue
    if ! git remote get-url "$name" >/dev/null 2>&1; then
      echo "Adding missing remote '$name' -> $url"
      git remote add "$name" "$url"
    fi
  done
}

ensure_required_origins

# ─── 1. Remove stale yorkie hooks ───────────────────────────────────────────
# Yorkie is no longer installed. Its hooks reference node_modules/yorkie which
# doesn't exist. Remove them so they don't interfere with pre-commit or git-lfs.
remove_yorkie_hooks() {
  local hook_file
  for hook_file in "$HOOKS_DIR"/*; do
    [ -f "$hook_file" ] || continue
    # Skip .sample files
    [[ "$hook_file" == *.sample ]] && continue
    # Check if it's a yorkie hooks
    if head -2 "$hook_file" | grep -q '#yorkie'; then
      rm "$hook_file"
    fi
  done
}

remove_yorkie_hooks

HOOK_PATH='export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$HOME/.pyenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/local/sbin:$PATH"'

# ─── 2. Make generated hooks find user-installed tools ──────────────────────
# IDEs can invoke Apple's/Xcode's git with a restricted PATH. Add the common
# macOS install locations used by pyenv, uv, Homebrew, and user-local tools so
# hook commands match the normal interactive shell more closely.
add_path_to_pre_commit_hooks() {
  local hook_name hook_file tmp_file
  for hook_name in pre-commit commit-msg; do
    hook_file="$HOOKS_DIR/$hook_name"
    [ -f "$hook_file" ] || continue
    grep -q 'File generated by pre-commit' "$hook_file" || continue
    if grep -q 'AllMyStorage hook PATH' "$hook_file"; then
      tmp_file="${hook_file}.tmp"
      {
        IFS= read -r first_line || true
        printf '%s\n' "$first_line"
        printf '# AllMyStorage hook PATH for IDE/Xcode Git environments.\n'
        printf '%s\n' "$HOOK_PATH"
        tail -n +4
      } <"$hook_file" >"$tmp_file"
      mv "$tmp_file" "$hook_file"
      chmod +x "$hook_file"
      continue
    fi

    tmp_file="${hook_file}.tmp"
    {
      IFS= read -r first_line || true
      printf '%s\n' "$first_line"
      printf '# AllMyStorage hook PATH for IDE/Xcode Git environments.\n'
      printf '%s\n' "$HOOK_PATH"
      cat
    } <"$hook_file" >"$tmp_file"
    mv "$tmp_file" "$hook_file"
    chmod +x "$hook_file"
  done
}

# git-lfs installs hooks that fail when Apple's/Xcode's git runs them without
# Homebrew on PATH. Keep the LFS commands active, but make sure those hooks can
# find git-lfs from normal macOS install locations first.
repair_git_lfs_hooks_path() {
  local hook_name hook_file lfs_command
  for hook_name in post-checkout post-commit post-merge pre-push; do
    hook_file="$HOOKS_DIR/$hook_name"
    [ -f "$hook_file" ] || continue
    if grep -q 'git lfs' "$hook_file" && grep -q 'git-lfs' "$hook_file"; then
      lfs_command="$hook_name"
      cat >"$hook_file" <<EOF
#!/bin/sh
# AllMyStorage hook PATH for IDE/Xcode Git environments.
$HOOK_PATH
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "git-lfs was not found on PATH for the $hook_name hook."; exit 2; }
git lfs $lfs_command "\$@"
EOF
      chmod +x "$hook_file"
    fi
  done
}

# ─── 3. Unset core.hooksPath if set ─────────────────────────────────────────
# Some tools (e.g. husky v9) set core.hooksPath which prevents .git/hooks from
# being used. We want .git/hooks to be the canonical hooks directory.
git config --unset-all core.hooksPath 2>/dev/null || true

# ─── 4. Install git-lfs hooks ───────────────────────────────────────────────
# git-lfs install writes its hooks (post-checkout, post-commit, post-merge, pre-push)
if command -v git-lfs >/dev/null 2>&1; then
  git lfs install --local >/dev/null 2>&1 || true
  "$REPO_ROOT/scripts/°base/init/git-lfs-full-path.sh" >/dev/null 2>&1 || true
fi
repair_git_lfs_hooks_path

# GitHub's LFS lock API can reject pushes when credentials are valid for git
# push but not for lock verification. This repo does not use LFS locks, so keep
# the generated pre-push hook from checking them for local GitHub HTTPS remotes.
if command -v python3 >/dev/null 2>&1; then
  python3 "$REPO_ROOT/scripts/°base/git/remote/fix_username.py" --fix-lfs-locks-only >/dev/null 2>&1 || true
fi

# ─── 5. Install pre-commit hooks ────────────────────────────────────────────
# Installs commit-msg and pre-commit hooks types as configured in
# .pre-commit-config.yaml
if command -v pre-commit >/dev/null 2>&1; then
  pre-commit install --hook-type pre-commit >/dev/null 2>&1 || true
  pre-commit install --hook-type commit-msg >/dev/null 2>&1 || true
  add_path_to_pre_commit_hooks
fi
